/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeepRouteImport } from './routes/deep'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShallowRouteImport } from './routes/shallow'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPostbackRouterRouteImport } from './routes/api/public/postback-router'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepRoute = DeepRouteImport.update({
  id: '/deep',
  path: '/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShallowRoute = ShallowRouteImport.update({
  id: '/shallow',
  path: '/shallow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPostbackRouterRoute = ApiPublicPostbackRouterRouteImport.update({
  id: '/api/public/postback-router',
  path: '/api/public/postback-router',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deep': typeof DeepRoute
  '/privacy': typeof PrivacyRoute
  '/shallow': typeof ShallowRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/postback-router': typeof ApiPublicPostbackRouterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deep': typeof DeepRoute
  '/privacy': typeof PrivacyRoute
  '/shallow': typeof ShallowRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/postback-router': typeof ApiPublicPostbackRouterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/deep': typeof DeepRoute
  '/privacy': typeof PrivacyRoute
  '/shallow': typeof ShallowRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/postback-router': typeof ApiPublicPostbackRouterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deep'
    | '/privacy'
    | '/shallow'
    | '/admin'
    | '/api/public/postback-router'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deep'
    | '/privacy'
    | '/shallow'
    | '/admin'
    | '/api/public/postback-router'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/deep'
    | '/privacy'
    | '/shallow'
    | '/_authenticated/admin'
    | '/api/public/postback-router'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeepRoute: typeof DeepRoute
  PrivacyRoute: typeof PrivacyRoute
  ShallowRoute: typeof ShallowRoute
  ApiPublicPostbackRouterRoute: typeof ApiPublicPostbackRouterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep': {
      id: '/deep'
      path: '/deep'
      fullPath: '/deep'
      preLoaderRoute: typeof DeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shallow': {
      id: '/shallow'
      path: '/shallow'
      fullPath: '/shallow'
      preLoaderRoute: typeof ShallowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/postback-router': {
      id: '/api/public/postback-router'
      path: '/api/public/postback-router'
      fullPath: '/api/public/postback-router'
      preLoaderRoute: typeof ApiPublicPostbackRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DeepRoute: DeepRoute,
  PrivacyRoute: PrivacyRoute,
  ShallowRoute: ShallowRoute,
  ApiPublicPostbackRouterRoute: ApiPublicPostbackRouterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
